version: '3'

services:
  geth-rpc-x-miner:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
      - "8002:8002"
    restart: always
    command: 
      --allow-insecure-unlock
      --datadir .
      --networkid 7878
      --port 30304
      --authrpc.port 8552

      --http
      --http.addr '0.0.0.0'
      --http.corsdomain "*"
      --http.port 8502
      --http.api 'personal,eth,net,web3,txpool,debug'

      --ws --ws.addr '0.0.0.0'
      --ws.origins "*"
      --ws.port 8002
      --ws.api 'personal,eth,net,web3,txpool,debug,engine'
      
      --mine
      --miner.threads=1
      --miner.etherbase=0x61224822ed31db4deA05c5784267c521f541Def5
    volumes:
      - ./:/blockchain